package com.auro.scholr.core.common;

public enum Status {

    LOADING,
    SUCCESS,
    FAIL,
    AUTH_FAIL,
    FAIL_400,
    FAIL_DB,

    ON_SHOW_DATA,
    ON_SHOW_ERROR,
    ON_SHOW_NO_INTERNET,
    ON_SHOW_SHIMMER,

    OK,
    HIDE_KEYBOARD,
    NO_INTERNET,
    DEFAULT_MSG,
    KYC_BUTTON_CLICK,
    KYC_RESULT_PATH,
    FACE_DETECTION_CALLBACK,
    DASHBOARD_API,
    UPLOAD_PROFILE_IMAGE,
    DEMOGRAPHIC_API,
    ASSIGNMENT_STUDENT_DATA_API,
    START_QUIZ_BUTON,
    AZURE_API,
    FRIEND_LEADER_BOARD_CLICK,
    STATE_LIST_ARRAY,
    DISTRICT_LIST_DATA,
    UPDATE_TEACHER_PROFILE_API,
    GET_TEACHER_DASHBOARD_API,
    SUBJECT_CLICK,
    CLASS_CLICK,
    SEND_MESSAGE_CLICK,
    DOCUMENT_CLICK,
    MESSAGE_SELECT_CLICK,
    GET_PROFILE_TEACHER_API,
    TEACHER_KYC_API,
    INVITE_FRIENDS_LIST,
    SEND_INVITE_API,
    SEND_INVITE_CLICK,
    NEXT_QUIZ_CLICK,
    ACCEPT_INVITE_CLICK,
    BOOK_TUTOR_SESSION_CLICK


}
